"""
数据模式模块
"""
from app.schemas.water_quality import (
    WaterQualityBase,
    WaterQualityCreate,
    WaterQualityUpdate,
    WaterQualityResponse,
    WaterQualityListResponse,
    WaterQualityQuery
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    Token,
    TokenData
)
from app.schemas.dashboard import (
    OverviewStatistics,
    RiverStatistics,
    QualityLevelDistribution,
    MonthlyTrend,
    IndicatorStatistics,
    RecentWaterQuality,
    DashboardResponse,
    RiverListResponse,
    MethodStatistics,
    MethodOverviewStatistics,
    MethodRiverStatistics,
    MethodQualityDistribution,
    MethodMonthlyTrend,
    MethodIndicatorStatistics,
    MethodDashboardResponse,
    MethodListResponse
)

__all__ = [
    "WaterQualityBase",
    "WaterQualityCreate", 
    "WaterQualityUpdate",
    "WaterQualityResponse",
    "WaterQualityListResponse", 
    "WaterQualityQuery",
    "UserBase",
    "UserCreate",
    "UserUpdate", 
    "UserResponse",
    "UserLogin",
    "Token",
    "TokenData",
    "OverviewStatistics",
    "RiverStatistics",
    "QualityLevelDistribution",
    "MonthlyTrend",
    "IndicatorStatistics",
    "RecentWaterQuality",
    "DashboardResponse",
    "RiverListResponse",
    "MethodStatistics",
    "MethodOverviewStatistics",
    "MethodRiverStatistics",
    "MethodQualityDistribution",
    "MethodMonthlyTrend",
    "MethodIndicatorStatistics",
    "MethodDashboardResponse",
    "MethodListResponse"
] 